--return {
--  "navarasu/onedark.nvim",
--  priority = 1000, -- load before other UI plugins
--  opts = {
--    style = "dark",
--    term_colors = true,
--    code_style = {
--      comments = "italic",
--      keywords = "none",
--      functions = "none",
--      strings = "none",
--      variables = "none",
--    },
--  },
--  config = function(_, opts)
--    require("onedark").setup(opts)
--    vim.cmd.colorscheme("onedark")
--  end,
--}
return {}
