-- Markdown quality-of-life: Glow previews + Headlines styling
return {
--  {
--    "ellisonleao/glow.nvim",
--    ft = { "markdown", "md", "mdx" },
--    cmd = "Glow",
--    opts = {
--      style = "dark",
--      width = 120,
--      border = "rounded",
--    },
--  },
--
--  {
--    "lukas-reineke/headlines.nvim",
--    ft = { "markdown", "md", "mdx" },
--    dependencies = { "nvim-treesitter/nvim-treesitter" },
--    opts = {
--      markdown = {
--        headline_highlights = {
--          "Headline1",
--          "Headline2",
--          "Headline3",
--          "Headline4",
--          "Headline5",
--          "Headline6",
--        },
--        fat_headlines = true,
--        fat_headline_upper_string = "====",
--        fat_headline_lower_string = "----",
--        bullet_highlights = {
--          "Headline1",
--          "Headline2",
--          "Headline3",
--          "Headline4",
--          "Headline5",
--          "Headline6",
--        },
--        bullets = { "-", "*", "+", "o" },
--      },
--    },
--    config = function(_, opts)
--      require("headlines").setup(opts)
--
--      local links = {
--        Headline1 = "Function",
--        Headline2 = "Type",
--        Headline3 = "Constant",
--        Headline4 = "Keyword",
--        Headline5 = "String",
--        Headline6 = "Identifier",
--        CodeBlock = "ColorColumn",
--        Dash = "Comment",
--      }
--
--      for group, link in pairs(links) do
--        vim.api.nvim_set_hl(0, group, { link = link, default = true })
--      end
--    end,
--  },
}
